{% set version = "3.4.0" %}

package:
  name: ijson
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/ijson/ijson-{{ version }}.tar.gz
  sha256: 5f74dcbad9d592c428d3ca3957f7115a42689ee7ee941458860900236ae9bb13

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=77.0
  run:
    - python >={{ python_min }}

test:
  imports:
    - ijson
    - ijson.backends
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/isagalaev/ijson
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Ijson is an iterative JSON parser with a standard Python iterator interface.
  doc_url: https://github.com/isagalaev/ijson
  dev_url: https://github.com/isagalaev/ijson

extra:
  recipe-maintainers:
    - rmax
    - synapticarbors
