{% set version = "3.5.0" %}

package:
  name: ijson
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/i/ijson/ijson-{{ version }}.tar.gz
  sha256: 94688760720e3f5212731b3cb8d30267f9a045fb38fb3870254e7b9504246f31

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-build-isolation --no-deps

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=77.0
  run:
    - python >={{ python_min }}

test:
  imports:
    - ijson
    - ijson.backends
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ICRAR/ijson
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Ijson is an iterative JSON parser with a standard Python iterator interface.
  doc_url: https://github.com/ICRAR/ijson
  dev_url: https://github.com/ICRAR/ijson

extra:
  recipe-maintainers:
    - rmax
    - synapticarbors
