{% set name = "ijson" %}
{% set version = "3.0" %}
{% set sha256sum = "13507564c2798a2af9250211b0be246ca75bbf499fd7375803d3f91dccc7c2c1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256sum }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - ijson

about:
  home: https://github.com/isagalaev/ijson
  license: BSD 3-clause
  license_file: LICENSE.txt
  summary: Ijson is an iterative JSON parser with a standard Python iterator interface.
  doc_url: https://github.com/isagalaev/ijson
  dev_url: https://github.com/isagalaev/ijson

extra:
  recipe-maintainers:
    - rmax
    - thermokarst
