travis:
  secure:
    BINSTAR_TOKEN: DPNEOEjr457fkVARiYFnFbgqB5yTQevdhlUduYywtQ60dlYyG/hZrW3lYeLa6lo6qXLp2fxCkLyNh5hUfIK4ASE7bFRvZi4e/ZBplTSfW8M483Ax4RhRf1xr1niwKihWpueF3K5EaQBGyek2j43iTa6OUeORKfH0IgaGQP7u5YzWHTuE/3PBXg/Y2sPd2rYEkM57fhY9NS45SnUqPAQKM+wlFIzkvKBXwFMq9BtIZxVlF5ye8h5SvAympmvJoIxSuDC9SmofnWikpd6h3sVizQ8L0fTlJepYSrvYbZI53QXnZsnUhSelNFsPUkujJkFwrZBaW3EkzM2xbEld6Pw8JgZsEvHYD00d5q94pSBlPQXCcHC00gm9ic6088pDzc64JhBD9INTEDwGMOVTob6DzeDk3Wcw68AwCUHINwbR5TJA5CCX9mzGyY9JiqvD8tHcIYpQbMlesi+HJTwDOGKTELsWb9jT3aHCZFE4HlwqFN2u61VHT5WmBGz3Q4Fn/2bZ25B0qt3Vj+/8QjEMbQ9XF0svVm3dUOL31W/W+p5KhSdwVIMnZUWVzx+HZuYOVSf9Dhk9iujlVB/PZSslyFIhSoyIHphg5hba780lFt23s+q3otrciqG/bPcMWVTCiazA2LaEOu4jxf//fEyLu2u8S1Ur6io2V9FfTAy5vhxQCzE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
